### ISSUE TITLE
Review Fairhurst Global Abstract

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-fairhurst-global#5]
@robfairh  : Julia is an undergraduate research assistant this semester who has taken the Stanford MOOC on scientific writing. Her work assignment is to help us with some of the editing tasks by suggesting edits which apply the lessons from that MOOC toward improved grammar, directness, brevity, impact, clarity, etc. I would like her to review this abstract for all of these things. Thank you for participating!

@juliaroessler Please read the pdf below and make suggestions (either as comments here in this issue or via pull request).

[fairhurst-global-abstract.pdf](https://github.com/arfc/2019-fairhurst-global/files/2847433/fairhurst-global-abstract.pdf)

For reference, the checklist:

- [ ] Articles such as "a" "the" "some" "any" and "each" appear where necessary.
- [ ] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty")
- [ ] Avoid run-on sentences.
- [ ] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [ ] reduce vague words (important, methodologic)
- [ ] reduce acronyms / jargon
- [ ] get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [ ] get rid of extraneous adverbs (very, really, quite, basically, generally)
- [ ] get rid of there are / there is
- [ ] turn negatives to positives (she was not often right -> she was usually wrong)
- [ ] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [ ] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [ ] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [ ] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes") 
- [ ] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [ ] data is plural (the data are critical)
- [ ] compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [ ] punctuation helps you to vary your sentence structure
- [ ] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [ ] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [ ] semicolon: connects two independent clauses. OR used to separate when the items in the list contain internal punctuation.
- [ ] use a colon to introduce a list, quote, explanation, conclusion, or amplification
- [ ] if there's a list in a sentence, it shouldn't come before the colon
- [ ] use a dash to insert something in the middle of the sentence. Don't overuse it.

**Comment by juliaroessler** [comment]
@robfairh : Here are some suggestions I have for your abstract! Feel free to reach out if you have any questions about them.

**Paragraph 1:**

- S1: “Nuclear fuel…” to make this opener clearer, it could be reworded as “Nuclear fuel cycle simulators require users to have prior knowledge regarding fuel cycles.”
- S2: “Sometimes…” to get rid of the “be” verb, an alternative sentence might be “Users must make calculations to find the amount of deployed facilities necessary to adequately represent a cycle” or something along those lines.
- S3: “Consequently…” can be shortened to just “The user must then run the simulator several times until it reflects reality.”
- S4: “A new…” – I would use dashes instead of parentheses because d3ploy is the most important noun in the sentence. Maybe something like “d3ploy [1] – a new Demand Driven Deployment Capability – is under development to…”
- S5: This sentence could use a little bit more detail! Why did the group want to carry out the simulations?, etc.
- S6 & S7: I’m not sure if these sentences are absolutely necessary here, since you are saving the details for the results section anyway.

**Paragraph 2:**

- Indent paragraph 2 to match paragraph 1!
- S1: Is it necessary to mention details like “project NEUP-FY16-10512” and the report mentioned in the following sentence? If not, you can edit them out of the abstract.
- S3: I would end the sentence like this: “…EG30 (Table I).”
- S4: “All the scenarios…” – In this sentence, dashes could also be used to appropriately set off the phrase “representing the current U.S. fuel cycle” instead of commas if you prefer. In addition, change “transition” to “transitioned” to match the verb tense of “started” earlier in the sentence.
- S5 & S6: These sentences can probably be combined to avoid repetition; “The simulations utilized d3ploy’s non-optimizing, deterministic-optimizing, and stochastic-optimizing algorithms to…”
- S7: “The results obtained…” I would edit this to make it more concise; for example, “The results obtained emphasize d3ploy’s ability to facilitate transition scenarios.”
